..\caget %* CTT:TEST_1-AI.SCAN
..\caget %* CTT:TEST_1-AI.INP
..\caget %* CTT:TEST_1-AI.EGU
..\caget %* CTT:CALC_BI.INAV
..\caget %* CTT:TEST_MBBO
..\caget %* CTT:TEST_MBBO.ZRVL
..\caget %* CTT:TEST_MBBO.DESC
..\caget %* CTT:TEST_STRING
..\caget %* CTT:STRING
..\caget %* CTT:STRING.OUT
..\caget %* CTT:STRING.DESC
..\caget %* CTT:TEST_WVF-CHAR
..\caget %* CTT:TEST_WVF-DOUBLE
..\caget %* CTT:TEST_WVF-FLOAT
..\caget %* CTT:TEST_WVF-FLOAT.NELM
..\caget %* CTT:TEST_WVF-LONG
..\caget %* CTT:TEST_WVF-SHORT
..\caget %* CTT:TEST_WVF-STRING
..\caget %* CTT:MOTOR
..\caget %* CTT:MOTOR.VELO
..\caget %* CTT:STATIC-LONGIN
..\caget %* CTT:STATIC-AO
..\caget %* CTT:STATIC-AO.OUT
..\caget %* CTT:RecordNameThatIsLongerThanFortyCharsForLongStringTest.NAME