../caget $1 CTT:TEST_1-AI.SCAN
../caget $1 CTT:TEST_1-AI.INP
../caget $1 CTT:TEST_1-AI.EGU
../caget $1 CTT:CALC_BI.INAV
../caget $1 CTT:TEST_MBBO
../caget $1 CTT:TEST_MBBO.ZRVL
../caget $1 CTT:TEST_MBBO.DESC
../caget $1 CTT:TEST_STRING
../caget $1 CTT:STRING
../caget $1 CTT:STRING.OUT
../caget $1 CTT:STRING.DESC
../caget $1 CTT:TEST_WVF-CHAR
../caget $1 CTT:TEST_WVF-DOUBLE
../caget $1 CTT:TEST_WVF-FLOAT
../caget $1 CTT:TEST_WVF-FLOAT.NELM
../caget $1 CTT:TEST_WVF-LONG
../caget $1 CTT:TEST_WVF-SHORT
../caget $1 CTT:TEST_WVF-STRING
../caget $1 CTT:MOTOR
../caget $1 CTT:MOTOR.VELO
../caget $1 CTT:STATIC-LONGIN
../caget $1 CTT:STATIC-AO
../caget $1 CTT:STATIC-AO.OUT
../caget $1 CTT:RecordNameThatIsLongerThanFortyCharsForLongStringTest.NAME